server:
  port: 2333
  address: 0.0.0.0
lavalink:
  server:
    password: 'renmei'
    sources:
      youtube: false
      soundcloud: true
    plugins:
      - name: youtube
        config:
          countryCode: US
